environment:

  matrix:

    - PYTHON: "C:\\Python38"
      PYTHON_VERSION: "Python 3.8 x86"
      IMAGEMAGICK_PLATFORM: "--x86"
    - PYTHON: "C:\\Python38-x64"
      PYTHON_VERSION: "Python 3.8 x64"

install:
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"

  # Check that we have the expected version and architecture for Python
  - "python --version"
  - "python -c \"import struct; print(struct.calcsize('P') * 8)\""

  # Update PIP version
  - ".\\appveyor\\build.cmd python -m pip install --user --upgrade pip"

  # Install AtlassianBot requirements
  - ".\\appveyor\\build.cmd python -m pip install -r requirements.txt"

  # Install CodeCov requirements
  - "python -m pip install codecov"

  # Install ImageMagick
  - choco install imagemagick.app --version 6.9.6.2 -y %IMAGEMAGICK_PLATFORM%

build: off

test_script:
  - "COPY plugins\\settings-sample.yml plugins\\settings.yml"
  - "coverage run --source=plugins,utils,imageproxy -m py.test -vv tests/"

after_test:
  - "coverage report"
  - "codecov --env PYTHON_VERSION APPVEYOR_REPO_BRANCH"
